metadata:
  author: "Alessandro Oggioni (CNR-IREA)"
  orcid: "https://orcid.org/0000-0002-7997-219X"
  license: "CC-BY 4.0"
  affiliation: "National Research Council of Italy – Institute for Electromagnetic Sensing of the Environment (CNR-IREA)"
  ror: "https://ror.org/02wxw4x45"
  description: >
    Workflow to automatically generate and publish RDF Turtle (.ttl) files 
    from a Google Sheet. The process supports eLTER-RI controlled vocabularies, 
    ensuring FAIRness by synchronizing generated RDF data with a Fuseki triple 
    store and Skosmos interface.
name: "eLTER-RI RDF Generation & FAIR Publishing  "
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
jobs:
  sheet2rdf:
    name: Sheet2RDF
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: conda-incubator/setup-miniconda@v3
        with:
          auto-update-conda: true
          python-version: "3.11"
          
      - name: prepare
        shell: bash -l {0}
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          conda create -n sheet2rdf python=3.11 pandas openpyxl
          conda activate sheet2rdf
          pip install gsheets

      - name: fetch
        shell: bash -l {0}
        env:
          FILE_NAME: ${{secrets.FILE_NAME}}
          GOOGLE_API_KEY: ${{secrets.GOOGLE_API_KEY}}
          SHEET_ID: ${{secrets.SHEET_ID}}
        run: |
          conda activate sheet2rdf
          python ./workflow/sheet2xls.py

      - name: conversion-xls2rdf
        env:
          FILE_NAME: ${{secrets.FILE_NAME}}
        run: |
          curl -L https://github.com/sparna-git/xls2rdf/releases/download/2.1.1/xls2rdf-app-2.1.1-onejar.jar -o xls2rdf.jar
          java -jar xls2rdf.jar convert -i $FILE_NAME.xlsx -o $FILE_NAME.ttl -l en
          echo "<http://vocabs.lter-europe.net/so/>" >> $FILE_NAME.ttl
          echo "   rdf:type skos:ConceptScheme" ;>> $FILE_NAME.ttl
          echo "	 rdf:type owl:Ontology ." >> $FILE_NAME.ttl
          mv xls2rdf.log ./logs/
          rm -f xls2rdf.jar

      - name: commit-artifacts
        run: |
          git add .
          git diff-index --quiet HEAD || git commit -m "New .ttl from Google sheet has been generated"
          git push

      #- name: publish-rdf
      # env:
      #    SKOSMOS_CREDENTIALS: ${{secrets.SKOSMOS_CREDENTIALS}}
      #    SKOSMOS_URL: ${{vars.SKOSMOS_URL}}
      #  run: |
      #    workflow/publish.sh
